### ISSUE TITLE
Demo doesnt work

### ISSUE THREAD

**Issue by M4GNV5** [nedpals/Aternos-v2#1]
The Demo page you are mentioning in the readme `http://labs.nedpalsdaily.tk/aternos/` isnt holding the actual rework of Aternos. :smirk:
the server returns either an empty page or sometimes
[![Cmd](http://i.imgur.com/Utwl5NU.png)]()

**Comment by nedpals** [comment]
Oops.. Sorry about that... The demo is now being moved to the GitHub page instead in the website. It is usually down for some reason.

**Comment by nedpals** [comment]
Updated: http://nedpals.github.io/aternos-v2 . It should be working in seconds.
